
package ru.karapetiandav.googlebooksapp.rest;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/*
* Generated by json2pojo
* */

public class ImageLinks {

    @SerializedName("smallThumbnail")
    @Expose
    private String smallThumbnailUrl;
    @SerializedName("thumbnail")
    @Expose
    private String thumbnailUrl;

    public String getSmallThumbnailUrl() {
        return smallThumbnailUrl;
    }

    public void setSmallThumbnailUrl(String smallThumbnailUrl) {
        this.smallThumbnailUrl = smallThumbnailUrl;
    }

    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }

}
